spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 80
  servlet:
    context-path: /identity
---
server:
  port: 80
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3309/${MYSQL_DATABASE}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: dev

jwt:
  signerKey: "hgHKoWb4RkgXz82ucDAD1cXQSyLPkHO+zcAnQxDpbQyNwHcywztLh4STeumzTA3k"