version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:spring
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: identity_service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - db
  db:
    image: mysql:8.0.36-debian
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_service
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  db-data: